# Chapter 5 - Dimensionality Reduction: Answers to the Review Questions

## Factual Question 1

**What is meant by the curse of dimensionality?**

**The curse of dimensionality** itself is the name for the fact that, in higher
dimensions, data can behave in ways we neither expect nor are used to from lower
dimensions (p. 218). The book demonstrates this with two concrete examples:

1. **Points become extreme.** If a point is chosen at random inside a 2-dimensional
   unit square, it can be shown mathematically that there is less than a 0.4% chance
   the point lands closer than 0.001 length units to an edge - i.e. it is very
   unlikely to be "extreme" in either dimension. Repeating the same reasoning for a
   100-dimensional unit hypercube gives a probability of just over 18%; for 1,000
   dimensions, over 86%; and for 10,000 dimensions, *"the probability is greater than
   99.999999%"* (p. 218). In other words, in high dimensions almost every point ends
   up being extreme in at least one of its many dimensions.
2. **Points become far apart.** Choosing two random points in a 2D unit square gives
   an average distance between them of about 0.52 length units; in 3D, about 0.66; and
   in a *1,000,000*-dimensional unit hypercube, the average distance becomes about 408
   length units (p. 219). More dimensions simply means more "room", so data points end
   up much farther apart on average. The practical implication: *"if we have a new
   data point that we want to predict, it will on average be further away from the
   data points a model has been trained on, the higher the dimension of the dataset...
   It therefore becomes harder to predict, and the risk of overfitting increases -
   i.e. that the model performs well on the data it was trained on but generalizes
   poorly to new, unseen data"* (p. 219).

## Factual Question 2

**What is dimensionality reduction, and why is it done?**

**Definition.** *"Dimensionality reduction means that we transform a dataset with a
given dimension into a lower number of dimensions. The result is that the dataset ends
up with a smaller number of variables. From a given set of variables, we thus get new
variables that are fewer in number"* (p. 220). 
**Why it is done - the three effects (Section 5.2.1, p. 220):**

1. *"Reduce the time it takes to train a model."* This is described as the main
   motivation - e.g. a model that is retrained every night simply needs to finish
   training within the time available.
2. *"A model trained on dimensionality-reduced data can sometimes achieve better
   predictive ability, even though it is often worse."* The book explains that
   predictive ability commonly gets *worse* after dimensionality reduction (because
   information is lost), which forces a tradeoff between training time and predictive
   ability - its own example: a classification model that takes 15 hours to train and
   reaches 70% accuracy might, after dimensionality reduction, take 8 hours to train
   and reach 65% accuracy; whether that tradeoff is worth it "depends on the case, and
   a tradeoff needs to be made" (p. 220). Occasionally, though, predictive ability
   *improves* after dimensionality reduction - e.g. because unnecessary noise is
   removed, preventing the model from overfitting to random noise instead of genuine
   patterns.
3. *"Being able to visualize data, even though it is not the original data."* If a
   high-dimensional dataset is reduced to two or three dimensions, it becomes possible
   to plot it (as in Figures 5.2 and 5.3, p. 221-222) - keeping in mind that what is
   plotted is a *transformed* version of the data, so a direct interpretation can be
   challenging. In higher dimensions (e.g. 10), this kind of visual interpretation
   becomes difficult and is rarely attempted.


## Factual Question 3

**Explain, in overview, how PCA works. Use Figure 5.4 on page 224 in your explanation.**

Covered in Section 5.3, *"Principalkomponentanalys (PCA)"* (p. 223-225).

**The core idea.** To perform a dimensionality reduction, data points can be
*projected* down onto a lower-dimensional hyperplane (a hyperplane is the
generalization, to any number of dimensions, of a line in 2D or a plane in 3D - see
the book's info box on p. 223). The key question is *how* to choose that hyperplane.
The book's answer: *"a reasonable way to do this is to choose the hyperplane that
retains as much information from the original dataset as possible. To do this, PCA
chooses the hyperplane that retains the highest share of variance"* (p. 223).

**Walking through Figure 5.4 (p. 224).** The left-hand panel of Figure 5.4 shows a
2-dimensional dataset (axes $x_1$ and $x_2$) together with three candidate lines that a
1-dimensional projection could be made onto: a solid line, a dashed line, and a dotted
line. The right-hand panel shows the result of projecting every point onto each of
those three lines in turn. Comparing the three right-hand strips, the points projected
onto the **solid line** are the most spread out - i.e. that projection retains the most
variance - followed by the dashed line, and finally the dotted line, whose projected
points are the most tightly bunched together (retaining the least variance). Since PCA
always wants to retain as much variance as possible, **the data would be projected onto
the solid line**.
**Finding the principal components.** Generalizing this idea, PCA works as follows:

1. It first identifies the axis that retains the **largest** share of variance in the
   original data. This axis does not need to align with any of the original axes - it
   points in whichever direction the data happens to spread out the most. In Figure
   5.4 this is the axis labelled $C_1$ (which corresponds to the solid line just
   discussed).
2. It then identifies a **second** axis that retains the next-largest share of
   variance, under one constraint: it must be **orthogonal** (perpendicular) to the
   first axis. This is $C_2$ in Figure 5.4. The book explicitly notes that although the
   dashed line by itself retains more variance than $C_2$ does, $C_2$ cannot be the
   dashed line, precisely because the dashed line is *not* orthogonal to $C_1$ - and
   orthogonality to all previous axes is a hard requirement (p. 223-224).
3. This continues - each new axis retaining the next-largest remaining share of
   variance, always orthogonal to every axis found so far - until there are as many new    axes as there were dimensions in the original data. **Each of these axes is called a principal component.**

## Reasoning Question 5
the general answer to Stina is: **maximizing pure predictive performance is only
one objective among several**, and time is frequently a competing one, in at least two
distinct places, as Kalle says:

1. **Training time** - directly addressed by the book (models retrained nightly, as it
   mentions, "simply need to be able to finish training within the time available"
   (p. 220); a model that is 2% more accurate but takes 10x as long to retrain every
   day may not be practical at all).
2. **Prediction (inference) time** - not spelled out with a numeric example in this
   chapter, but a direct extension of the same reasoning: a model is not only trained
   once, it is normally *used* to make predictions repeatedly afterwards, sometimes at
   very high volume or with strict latency requirements (e.g. a fraud-detection model
   that must score a transaction in milliseconds, or a recommendation model serving
   millions of requests). If the most accurate model available is also the slowest one
   to run at prediction time, it may be entirely unusable in such a setting even though
   it "wins" on accuracy in isolation.

**When is it reasonable to want predictive ability to be as high as possible?**
Whenever the cost of a wrong prediction is very high and time/compute is comparatively
cheap or not time-critical - for example, a medical diagnosis model, a one-off
scientific analysis, or a model retrained rarely (e.g. once a quarter) where a few
extra hours of training time genuinely does not matter. In such cases, spending far
more time to buy a percentage point of accuracy can be entirely justified.

**When can chasing maximum predictive ability be a bad idea?** When it is not
matched by a real need for that accuracy, but does carry a real cost - for example: a
model that must run on a mobile phone or embedded device with limited compute and
battery; a model that must respond to a user within a fraction of a second (e.g. typing
suggestions, ad ranking, or a chatbot); a model that must be retrained frequently
(nightly or hourly) on fresh data, where a marginally more accurate but far slower
pipeline would simply never finish in time; or a case where the achievable accuracy
gain is small (e.g. 70% to 71%) but the added time or complexity is large - the
book's own framing of "is this worth it? A tradeoff needs to be made" (p. 220) applies
directly. In short: predictive performance is one important axis, but it should be
weighed against training time and prediction time whenever those are constrained,
exactly as Kalle argues.


## Reasoning Question 6
**Why this happens.** Every principal component that PCA produces is a specific linear
combination of *all* of the original variables at once (the axis that happens to point
in the direction of maximum remaining variance, subject to being orthogonal to the
earlier components). A principal component is therefore not "one of the original
variables, just renamed" - it is a mathematical blend of all of them, weighted in
whatever proportions maximize retained variance. There is generally no reason that
blend should correspond to anything meaningful in the real world (such as "weight" or
"height" on their own), so the new axes $z_1, z_2, \dots$ typically cannot be given a
clean real-world label or unit the way the original variables could.

**Practical consequence.** After a PCA, we can still use the transformed data
perfectly well for its intended purpose - training a model faster, or visualizing
high-dimensional data in 2D/3D (Section 5.2.1's listed benefits) - but we give up the
ability to explain a prediction, or a plotted axis, in terms of the original,
meaningful variables. For example, we can no longer say "the model's decision was
driven mainly by *mileage*" once *mileage* has been folded into several principal
components together with many other variables - we could only say it was driven by,
e.g., "principal component 1", which is a mix of several original variables at once.
This is exactly the price the book refers to when it says variable interpretation is
"a price we pay" for dimensionality reduction (p. 220).


## Reasoning Question 8

In [2]:

import numpy as np
from sklearn.decomposition import PCA

# Creating a dataset with 3 features/columns
X = np.random.rand(1000, 3)
print(X[0:5])

# Reducing the data to 2 dimensions
pca = PCA(n_components=2)
X2D = pca.fit_transform(X)
print(X2D[0:5])

# "Recreating" the data to 3 dimensions
X3D_inv = pca.inverse_transform(X2D)
# Not exactly equal since some information was lost in the transformation
print(np.allclose(X3D_inv, X))

[[0.74388111 0.91520814 0.10061768]
 [0.67162796 0.92679453 0.38341308]
 [0.25620686 0.93193074 0.34012087]
 [0.2635057  0.96288305 0.16159009]
 [0.48949608 0.85942322 0.9893384 ]]
[[-0.60685926 -0.02413217]
 [-0.38636792  0.13918803]
 [-0.19828261 -0.15001938]
 [-0.33735385 -0.26591045]
 [ 0.14900629  0.44525109]]
False


This is (up to the exact random values, since no `np.random.seed(...)` is fixed here)
the same worked example the book itself uses to demonstrate `PCA.inverse_transform()`,
Section 5.3, p. 227-228.

**Line by line, what the code does:**

1. `X = np.random.rand(1000, 3)` creates a synthetic dataset of 1,000 rows and 3
   columns (3 "features"), with every value drawn uniformly at random between 0 and 1.
   `print(X[0:5])` prints the first 5 rows, confirming there are 3 columns.
2. `pca = PCA(n_components=2)` creates a PCA model that will keep exactly **2**
   principal components (an explicit, manually chosen number of dimensions to keep -
   as opposed to Question 3's `PCA(n_components=0.7)`, which instead picks the number
   of components automatically to reach a target share of variance).
3. `X2D = pca.fit_transform(X)` does two things at once: it *fits* the PCA model on
   `X` (finding the 2 orthogonal directions of maximum variance in the 3-dimensional
   data, exactly as described for Question 3) and *transforms* `X` into that new
   2-dimensional space. `print(X2D[0:5])` prints the first 5 rows of the result -
   this now has only **2** columns instead of 3, confirming the dimensionality
   reduction from 3D to 2D.
4. `X3D_inv = pca.inverse_transform(X2D)` takes the reduced 2D data and projects it
   back into the *original* 3-dimensional space, using the same principal components
   found in step 3.
5. `np.allclose(X3D_inv, X)` checks whether this reconstructed 3D data (`X3D_inv`) is
   (numerically, within a small tolerance) identical to the original data (`X`).

**Interpreting the result: the final `print(...)` prints `False`.** Reconstructing the
data from its 2D projection does **not** exactly recover the original 3D data. This is
exactly the point the book makes about PCA (p. 227-228): *"the result is, however, not
the same, because information is lost when we perform a PCA."* Going from 3 dimensions
down to 2 necessarily throws away the small amount of variance that lived in the
direction of the 3rd (discarded) principal component; `inverse_transform()` can put the
data back into a 3-dimensional-*shaped* array, but it has no way to recover information
that was never kept in the first place - so `X3D_inv` ends up close to, but not
identical to, the original `X`. This is a direct, hands-on illustration of the general
principle already seen in Reasoning Question 6: a PCA transformation is **lossy**, and
that loss is exactly the price paid in exchange for a lower-dimensional dataset.

We reproduce this exact code below and run it for real, so the printed values can be
inspected directly (since no random seed is fixed in the question, the specific numbers
will differ slightly from the book's own printed output and will also differ every time
this cell is re-run - but the conclusion, `False`, will always be the same, for the
reason explained above).
